#!/usr/bin/env python3
"""Daily workout video analysis with local Ollama + email digest."""

# /// script
# requires-python = ">=3.14"
# dependencies = ["openai", "psutil"]
# ///

import argparse
import json
import os
import sqlite3
import sys
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from logging.handlers import RotatingFileHandler
from pathlib import Path
import logging
import smtplib

import psutil
from openai import OpenAI


def setup_logging(log_path: Path) -> logging.Logger:
    """Configure logger with file rotation."""
    log_path.parent.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger("workout_digest")
    logger.setLevel(logging.DEBUG)

    handler = RotatingFileHandler(log_path, maxBytes=5*1024*1024, backupCount=3)
    formatter = logging.Formatter("[%(asctime)s] %(levelname)s: %(message)s", "%H:%M:%S")
    handler.setFormatter(formatter)
    logger.addHandler(handler)

    return logger


def ram_state() -> str:
    """Return RAM state: 'ok' | 'caution' | 'tight' | 'critical'."""
    available_gb = psutil.virtual_memory().available / (1024**3)
    if available_gb < 0.2:
        return "critical"
    elif available_gb < 0.5:
        return "tight"
    elif available_gb < 1.0:
        return "caution"
    else:
        return "ok"


def ollama_is_up(model: str, logger: logging.Logger) -> bool:
    """Check if Ollama is running and model is available."""
    try:
        client = OpenAI(base_url="http://localhost:11434/v1", api_key="ollama")
        client.models.list()
        logger.info(f"✓ Ollama is up, using model {model}")
        return True
    except Exception as e:
        logger.error(f"Ollama not available at http://localhost:11434/v1: {e}")
        return False


def db_connect(db_path: Path) -> sqlite3.Connection:
    """Open state DB."""
    con = sqlite3.connect(db_path)
    con.execute("PRAGMA journal_mode=WAL")
    return con


def load_pending_videos(db: sqlite3.Connection, data_root: Path, logger: logging.Logger) -> list[dict]:
    """Load all videos that have been Gemma-analyzed but not yet Claude-analyzed."""
    cursor = db.execute(
        "SELECT sha, gemma_json_path FROM videos WHERE gemma_done_at IS NOT NULL AND claude_done_at IS NULL ORDER BY discovered_at DESC"
    )
    pending = []
    for sha, json_path in cursor.fetchall():
        json_file = data_root / "data" / "videos" / f"{sha}.json"
        if json_file.exists():
            pending.append({"sha": sha, "json_path": json_file})
        else:
            logger.warning(f"JSON file not found for {sha}: {json_file}")

    return pending


def build_video_summary(json_path: Path, logger: logging.Logger) -> dict | None:
    """
    Load video JSON and extract summary for Claude.
    Returns None if not a workout video.
    """
    try:
        data = json.loads(json_path.read_text())
    except Exception as e:
        logger.error(f"Could not read {json_path}: {e}")
        return None

    workout_summary = data.get("workout_summary", {})
    if not workout_summary.get("is_workout"):
        return None

    # Collect form_notes from frames
    form_notes = set()
    for frame in data.get("frames", []):
        if frame.get("workout") and frame["workout"].get("form_notes"):
            note = frame["workout"]["form_notes"].strip()
            if note and note not in form_notes:
                form_notes.add(note)

    return {
        "file_name": json_path.stem,
        "workout_summary": workout_summary,
        "form_notes": list(form_notes)[:5]  # Top 5 unique notes
    }


def build_claude_prompt(summaries: list[dict], date_label: str) -> str:
    """Compose the daily digest prompt."""
    if not summaries:
        return ""

    video_data = "\n\n".join([
        f"**Video: {s['file_name']}**\n"
        f"Exercises: {', '.join(s['workout_summary'].get('exercises', ['unknown']))}\n"
        f"Equipment: {', '.join(s['workout_summary'].get('equipment', ['unknown']))}\n"
        f"Body focus: {', '.join(s['workout_summary'].get('body_focus', ['unknown']))}\n"
        f"Intensity: {s['workout_summary'].get('peak_intensity', 'unknown')}\n"
        f"Environment: {s['workout_summary'].get('environment', 'unknown')}\n"
        f"Frame observations:\n" + "\n".join(f"  - {note}" for note in s['form_notes'])
        for s in summaries
    ])

    return f"""You are a personal fitness coach reviewing automatic workout footage analysis.
Below are frame-by-frame observations from {len(summaries)} workout videos recorded on {date_label}.
The observations were generated by a local vision model analyzing keyframes extracted from the videos.

For each video, provide:
1. Overall assessment (2-3 sentences)
2. Positive form observations (what looks good)
3. Form concerns worth addressing (be specific: which exercise, which cue)
4. One suggested focus for the next session

If you identify ANY safety concerns (injury risk, dangerous form, improper technique), flag them separately at the top with a **[SAFETY ALERT]** header.

--- VIDEO ANALYSIS DATA ---

{video_data}

---

Provide actionable feedback in a supportive tone."""


def call_ollama(prompt: str, model: str, logger: logging.Logger) -> str | None:
    """Call local Ollama model for the digest synthesis."""
    try:
        client = OpenAI(base_url="http://localhost:11434/v1", api_key="ollama")
        response = client.chat.completions.create(
            model=model,
            max_tokens=2048,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        logger.error(f"Ollama API call failed: {e}")
        return None


def render_html_email(claude_response: str, video_count: int, had_alerts: bool) -> str:
    """Render HTML email body."""
    alert_banner = ""
    if had_alerts:
        alert_banner = """
        <div style="background-color: #ff4444; color: white; padding: 12px; margin-bottom: 20px; border-radius: 4px; font-weight: bold;">
            ⚠️ SAFETY ALERTS DETECTED — Review form concerns below
        </div>
        """

    return f"""
    <html>
    <body style="font-family: sans-serif; color: #333; line-height: 1.6;">
        <div style="max-width: 700px; margin: 0 auto;">
            <h1 style="border-bottom: 2px solid #4CAF50; padding-bottom: 10px;">Workout Form Digest</h1>
            <p><strong>Videos analyzed:</strong> {video_count}</p>
            {alert_banner}
            <pre style="background-color: #f5f5f5; padding: 15px; border-radius: 4px; overflow-x: auto;">
{claude_response}
            </pre>
            <hr style="border: none; border-top: 1px solid #ddd; margin: 30px 0;">
            <p style="color: #888; font-size: 12px;">
                Generated by automatic workout video analysis pipeline (Gemma + Claude).
                <br/>
                <a href="https://github.com/karlmarx/karl-infra">View source</a>
            </p>
        </div>
    </body>
    </html>
    """


def send_email(
    html_body: str,
    plain_text: str,
    subject: str,
    from_addr: str,
    to_addr: str,
    app_password: str,
    logger: logging.Logger
) -> bool:
    """Send email via Gmail SMTP."""
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = from_addr
        msg["To"] = to_addr

        msg.attach(MIMEText(plain_text, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=10) as server:
            server.login(from_addr, app_password)
            server.sendmail(from_addr, [to_addr], msg.as_string())

        logger.info(f"✓ Email sent to {to_addr}")
        return True

    except Exception as e:
        logger.error(f"✗ Failed to send email: {e}")
        return False


def mark_done(
    db: sqlite3.Connection,
    shas: list[str],
    digest_sent: bool,
    had_alerts: bool,
    logger: logging.Logger
):
    """Mark videos as Claude-analyzed and emailed."""
    try:
        now = datetime.now().isoformat()
        for sha in shas:
            db.execute(
                "UPDATE videos SET claude_done_at = ?, emailed_at = ? WHERE sha = ?",
                (now if digest_sent else None, now if digest_sent else None, sha)
            )
        db.commit()
        logger.info(f"Marked {len(shas)} videos complete")
    except Exception as e:
        logger.error(f"Could not update DB: {e}")


def main():
    """Main digest entry point."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Print email without sending")
    parser.add_argument("--force-date", help="Process only videos from YYYY-MM-DD")
    args = parser.parse_args()

    data_root = Path(os.getenv("WORKOUT_DATA_ROOT", "/Users/kmx/projects/local-vlm-analysis"))
    ollama_model = os.getenv("OLLAMA_MODEL", "gemma4:26b")
    gmail_user = os.getenv("GMAIL_USER", "")
    gmail_app_pwd = os.getenv("GMAIL_APP_PASSWORD", "")
    digest_to = os.getenv("DIGEST_TO", "")
    log_path = Path.home() / ".local/share/workout-pipeline/digest-stdout.log"
    db_path = Path.home() / ".local/share/workout-pipeline/state.db"

    logger = setup_logging(log_path)
    logger.info(f"Starting daily digest (using Ollama {ollama_model})")

    if ram_state() in ["tight", "critical"]:
        logger.warning(f"RAM state {ram_state()}, skipping digest")
        return 0

    if not ollama_is_up(ollama_model, logger):
        logger.error("Ollama is not running. Start with: ollama serve")
        return 1

    if not gmail_user or not gmail_app_pwd or not digest_to:
        logger.error("Missing env vars: GMAIL_USER, GMAIL_APP_PASSWORD, DIGEST_TO")
        return 1

    db = db_connect(db_path)
    pending = load_pending_videos(db, data_root, logger)

    if not pending:
        logger.info("No pending videos, exiting")
        return 0

    logger.info(f"Found {len(pending)} pending videos")

    # Build summaries
    summaries = []
    for video_info in pending:
        summary = build_video_summary(video_info["json_path"], logger)
        if summary:
            summaries.append(summary)

    if not summaries:
        logger.info("No workout videos in pending set, skipping")
        db.close()
        return 0

    # Build Claude prompt
    today = datetime.now().strftime("%Y-%m-%d")
    prompt = build_claude_prompt(summaries, today)

    if not prompt:
        logger.error("Could not build Claude prompt")
        db.close()
        return 1

    logger.info(f"Built prompt for {len(summaries)} workout videos, calling Ollama {ollama_model}...")

    # Call Ollama
    claude_response = call_ollama(prompt, ollama_model, logger)
    if not claude_response:
        logger.error("Ollama call failed")
        db.close()
        return 1

    # Check for alerts
    alert_keywords = ["injury risk", "dangerous", "avoid", "pain", "strain", "hyperextend", "improper form", "safety alert"]
    had_alerts = any(keyword in claude_response.lower() for keyword in alert_keywords)

    # Determine subject line
    if had_alerts:
        subject = f"[ALERT] Workout Form Digest — {today}"
    else:
        subject = f"[Workout] Daily Form Digest — {today}"

    # Render email
    html_body = render_html_email(claude_response, len(summaries), had_alerts)
    plain_text = f"Workout Analysis for {today}\n\n{claude_response}"

    if args.dry_run:
        logger.info("DRY RUN — printing email")
        print(f"Subject: {subject}")
        print(f"To: {digest_to}")
        print(f"\n{plain_text}")
        db.close()
        return 0

    # Send email
    shas = [v["sha"] for v in pending if build_video_summary(v["json_path"], logger)]
    success = send_email(html_body, plain_text, subject, gmail_user, digest_to, gmail_app_pwd, logger)

    if success:
        mark_done(db, shas, True, had_alerts, logger)

    db.close()
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
