#!/usr/bin/env python3
"""Update README.md with recent commits and current date.

Reads recent_commits.md (generated by the GitHub Actions workflow)
and splices it into the Recent Changes section of README.md.
"""

import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
COMMITS_FILE = ROOT / "recent_commits.md"

START_MARKER = "<!-- RECENT_CHANGES_START -->"
END_MARKER = "<!-- RECENT_CHANGES_END -->"


def build_recent_changes(commits_path: Path) -> str:
    """Parse recent_commits.md into markdown for the README."""
    if not commits_path.exists():
        return f"{START_MARKER}\n_No recent commits data._\n{END_MARKER}"

    raw = commits_path.read_text(encoding="utf-8").strip()
    if not raw:
        return f"{START_MARKER}\n_No recent commits data._\n{END_MARKER}"

    # Filter to last 7 days of commits and limit per repo
    lines = []
    for line in raw.splitlines():
        lines.append(line)

    return f"{START_MARKER}\n{chr(10).join(lines)}\n{END_MARKER}"


def update_readme(readme_path: Path, recent_changes: str) -> bool:
    """Replace the Recent Changes section and update the date. Returns True if changed."""
    content = readme_path.read_text(encoding="utf-8")
    original = content

    # Update date
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    content = re.sub(
        r"Last update: \d{4}-\d{2}-\d{2}",
        f"Last update: {today}",
        content,
    )

    # Replace recent changes section
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    content = pattern.sub(recent_changes, content)

    if content != original:
        readme_path.write_text(content, encoding="utf-8")
        return True
    return False


def main() -> None:
    recent_changes = build_recent_changes(COMMITS_FILE)
    changed = update_readme(README, recent_changes)
    if changed:
        print("README.md updated.")
    else:
        print("README.md unchanged.")


if __name__ == "__main__":
    main()
